title: Dev Journal
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/liamstamper
  LinkedIn: https://linkedin.com/in/liamstamper

aux_links_new_tab: true
